// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLBpLriojEQSRsIlW9ajDzKBZcN6WdOzk',
    appId: '1:594253736109:web:ecf158459909753abb3e24',
    messagingSenderId: '594253736109',
    projectId: 'bulletpoints-paul-wennin',
    authDomain: 'bulletpoints-paul-wennin.firebaseapp.com',
    storageBucket: 'bulletpoints-paul-wennin.appspot.com',
    measurementId: 'G-P12Z52SN4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY7ND8wSjuJLlfFDpWhEbLweRFCWkkZG4',
    appId: '1:594253736109:android:eb9492763bac187cbb3e24',
    messagingSenderId: '594253736109',
    projectId: 'bulletpoints-paul-wennin',
    storageBucket: 'bulletpoints-paul-wennin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8MoSNFqmhF_B6yrEDAPPB8CqTZYSp9vA',
    appId: '1:594253736109:ios:e5cf669c8055a329bb3e24',
    messagingSenderId: '594253736109',
    projectId: 'bulletpoints-paul-wennin',
    storageBucket: 'bulletpoints-paul-wennin.appspot.com',
    iosBundleId: 'com.paulwennin.bulletpoints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8MoSNFqmhF_B6yrEDAPPB8CqTZYSp9vA',
    appId: '1:594253736109:ios:f3bd1b2c5e5c8c93bb3e24',
    messagingSenderId: '594253736109',
    projectId: 'bulletpoints-paul-wennin',
    storageBucket: 'bulletpoints-paul-wennin.appspot.com',
    iosBundleId: 'com.paulwennin.bulletpoints.RunnerTests',
  );
}
